image:
  file: .gitpod.Dockerfile

tasks:
  - command: 'java -version && mvn --version'

vscode:
  extensions:
    - vscjava.vscode-maven@0.21.2:tFEkt2FqLujaNTLU5AmRiQ==
    - vscjava.vscode-java-test@0.24.2:K9XH858+UGOKjfN3qRW15Q==